### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by MalinJarvius** [pharmbio/plaid#16]
Hi, I try to generate a layout with 49 compounds (2 replicates, 3 doses), 5 ref compounds (2 replicates, 3 doses) and 20 DMSO controls. PLAID doesn't generate a layout.

**Comment by andreina-francisco** [comment]
Hi Malin! Could you give me more details? Following your description, I tried it out, and it works, at least at the moment. I'm attaching the test I did, which you can try on the website (note that you need to change the extension from .txt to .json)

[Malin.json.txt](https://github.com/pharmbio/plaid/files/11274151/Malin.json.txt)
