### ISSUE TITLE
No output / returns to "Submit form" page

### ISSUE THREAD

**Issue by shntnu** [pharmbio/plaid#17]
Thanks for creating this!

The app does not produce an output when provided the attached config (which was generated by app). It shows "Your plate layout is being calculated. This process can take several minutes..." and then returns to the previous page.

[config.json](https://github.com/pharmbio/plaid/files/14076255/config.json)

**Comment by andreina-francisco** [comment]
Dear Shantanu,

I think you found one of the strange cases for which the online version runs out of memory. I'm currently working on fixing this. It can be run locally with MiniZinc. I'm including here some examples of what I get in csv format, but saved as txt so GitHub won't complain. 

But perhaps you actually had a different layout in mind? As it is right now, you get 2 plates with 40 compounds * 3 replicates each, plus 4 replicates of each positive control and 16 negative. Perhaps you don't actually want the empty border? Or perhaps you wanted more controls?

[shntnu-1.txt](https://github.com/pharmbio/plaid/files/14259921/shntnu-1.txt)
[shntnu-2.txt](https://github.com/pharmbio/plaid/files/14260358/shntnu-2.txt)

**Comment by shntnu** [comment]
Thank you so much for looking into this! 

> I think you found one of the strange cases for which the online version runs out of memory. I'm currently working on fixing this. It can be run locally with MiniZinc. I'm including here some examples of what I get in csv format, but saved as txt so GitHub won't complain.

Noted

> But perhaps you actually had a different layout in mind? As it is right now, you get 2 plates with 40 compounds * 3 replicates each, plus 4 replicates of each positive control and 16 negative. Perhaps you don't actually want the empty border? Or perhaps you wanted more controls?

We did want empty borders, but we wanted 36 controls so maybe I messed that up – I think that was because I indicated 8 replicates for the 8 poscons but we wanted only n=4 replicates. Thanks for pointing this out. I'll report back if we are stuck but you can otherwise close this out.

Thanks again!
